In [1]:
from relbench.datasets import dataset_names, get_dataset

In [2]:
dataset_names

['amazon_reviews', 'stack_exchange', 'fake_reviews']

In [3]:
dataset = get_dataset(
    name="stack_exchange",
)
dataset

StackExchangeDataset()

In [4]:
dataset.val_timestamp, dataset.test_timestamp

(Timestamp('2019-09-12 00:00:00'), Timestamp('2021-09-12 00:00:00'))

In [5]:
dataset.db.table_dict.keys()

dict_keys(['posts', 'badges', 'postLinks', 'votes', 'comments', 'users', 'postHistory'])

In [6]:
dataset.db.table_dict["posts"].df

,Id,OwnerUserId,LastEditorUserId,PostTypeId,AcceptedAnswerId,ParentId,OwnerDisplayName,LastEditorDisplayName,Title,Tags,ContentLicense,Body,CreationDate
0,0,7,<NA>,1,15.0,<NA>,None,None,Eliciting priors from experts,<bayesian><prior><elicitation>,CC BY-SA 2.5,<p>How should I elicit prior distributions fro...,2010-07-19 19:12:12
1,1,20,<NA>,1,59.0,<NA>,None,user88,What is normality?,<distributions><normality-assumption>,CC BY-SA 2.5,<p>In many different statistical methods there...,2010-07-19 19:12:57
2,2,15,153,1,5.0,<NA>,None,None,What are some valuable Statistical Analysis op...,<software><open-source>,CC BY-SA 2.5,<p>What are some valuable Statistical Analysis...,2010-07-19 19:13:28
3,3,19,<NA>,1,135.0,<NA>,None,None,Assessing the significance of differences in d...,<distributions><statistical-significance>,CC BY-SA 2.5,<p>I have two groups of data. Each with a dif...,2010-07-19 19:13:31
4,4,19,19,2,NaN,2,None,None,None,None,CC BY-SA 2.5,"<p>The R-project</p>\n\n<p><a href=""http://www...",2010-07-19 19:14:43
...,...,...,...,...,...,...,...,...,...,...,...,...,...
357192,357192,264770,<NA>,2,NaN,336973,None,None,None,None,CC BY-SA 4.0,<p>The red lines show negative effects (i.e. a...,2021-09-11 23:20:13
357193,357193,278332,<NA>,1,544378.0,<NA>,None,None,Connection between grey scale and intensity in...,<matrix><image-processing>,CC BY-SA 4.0,<p>Let A be a image matrix where each element ...,2021-09-11 23:25:30
357194,357194,128599,128599,2,NaN,357190,None,None,None,None,CC BY-SA 4.0,"<p>If <span class=""math-container"">$\mathbf{x}...",2021-09-11 23:27:47
357195,357195,278333,<NA>,1,544390.0,<NA>,None,None,Nonlinear unbiased estimator with strictly sma...,<regression>,CC BY-SA 4.0,<p>I want to find the following example: Const...,2021-09-11 23:58:02
357440,357440,<NA>,261785,1,NaN,<NA>,JIN ZHANG,None,How to calculate LÃ©vy random number,<distributions><algorithms><random-generation>...,CC BY-SA 4.0,"<p>The calculation process of the <a href=""htt...",2021-09-08 15:30:46

In [7]:
dataset.task_names

['user_contribution', 'question_popularity']

In [9]:
task = dataset.get_task("user_contribution")

Downloading file 'stack_exchange/tasks/user_contribution.zip' from 'https://relbench.stanford.edu/staging_data/stack_exchange/tasks/user_contribution.zip' to '/afs/cs.stanford.edu/u/kexinh/.cache/relbench'.
100%|âââââââââââââââââââââââââââââââââââââ| 1.01M/1.01M [00:00<00:00, 1.27GB/s]

In [10]:
task.train_table.df

       OwnerUserId  timestamp  contribution
0                0 2017-09-12             1
1                2 2017-09-12             0
2                4 2017-09-12             0
3                5 2017-09-12             1
4                6 2017-09-12             0
...            ...        ...           ...
97330        15264 2011-09-14             1
97331        15669 2011-09-14             0
97332        16601 2011-09-14             0
97333        17494 2011-09-14             1
97334        17938 2011-09-14             0

[97335 rows x 3 columns]

In [11]:
task.val_table.df

       OwnerUserId  timestamp  contribution
0                0 2019-09-12             1
1                2 2019-09-12             0
2                4 2019-09-12             0
3                5 2019-09-12             0
4                6 2019-09-12             0
...            ...        ...           ...
74859       225161 2019-09-12             1
74860       241823 2019-09-12             1
74861       247436 2019-09-12             1
74862       268097 2019-09-12             1
74863       290585 2019-09-12             0

[74864 rows x 3 columns]

In [13]:
task.test_table.df

       timestamp  OwnerUserId
0     2021-09-12            0
1     2021-09-12            2
2     2021-09-12            4
3     2021-09-12            5
4     2021-09-12            6
...          ...          ...
94675 2021-09-12       278332
94676 2021-09-12       278333
94677 2021-09-12       278663
94678 2021-09-12       280795
94679 2021-09-12       290585

[94680 rows x 2 columns]

In [15]:
import numpy as np

pred = np.array([0] * len(task.test_table.df))
task.evaluate(pred)

{'accuracy': 0.9258449514152937, 'f1': 0.0, 'roc_auc': 0.5}